server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:h2:mem:movies
    driver-class-name: org.h2.Driver
  username: penta
  password: bar

feign:
  hystrix:
    enabled: true

