server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:h2:mem:reviews
    driver-class-name: org.h2.Driver
    username: penta
    password: bar
